# Generated by Django 3.0 on 2025-02-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_migrate_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
