# Generated by Django 5.1.6 on 2025-03-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_auto_20250224_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='letting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
